POST http://localhost:5000/api/signup
Content-Type: application/json

{
  "username": "oliver1",
  "email": "oliver1@example.com",
  "password": "12345"
}


### Signup with email + hashed password
POST http://localhost:5000/api/signup
Content-Type: application/json

{
  "username": "oliver",
  "email": "oliver@example.com",
  "password": "12345"
}

### Login with bcrypt
POST http://localhost:5000/api/login
Content-Type: application/json

{
  "username": "oliver",
  "password": "12345"
}

### Signup (with email + hashed password)
POST http://localhost:5000/api/signup
Content-Type: application/json

{
  "username": "oliverjwt",
  "email": "oliverjwt@example.com",
  "password": "12345"
}

### Login (get JWT token)
POST http://localhost:5000/api/login
Content-Type: application/json

{
  "username": "oliverjwt",
  "password": "12345"
}

### Protected route (favorites example)
GET http://localhost:5000/api/favorites
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMDRiZGFkMDcxZWZiYmNhYTJjM2RkNiIsInVzZXJuYW1lIjoib2xpdmVyand0IiwiZW1haWwiOiJvbGl2ZXJqd3RAZXhhbXBsZS5jb20iLCJpYXQiOjE3Nzg2OTU2NzQsImV4cCI6MTc3ODY5OTI3NH0.IYo3SgQl7YfM52Qf8GAHr1LfpMQijBnmiHkUaUqdWZw

### Login to get token
POST http://localhost:5000/api/login
Content-Type: application/json

{
  "username": "oliverjwt",
  "password": "12345"
}

### Valid token
GET http://localhost:5000/api/favorites
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMDRiZGFkMDcxZWZiYmNhYTJjM2RkNiIsInVzZXJuYW1lIjoib2xpdmVyand0IiwiZW1haWwiOiJvbGl2ZXJqd3RAZXhhbXBsZS5jb20iLCJpYXQiOjE3Nzg3ODA5NjYsImV4cCI6MTc3ODc4NDU2Nn0.LWjmMsS-izGGUJq3VS3Gxli9CLmP9fpxJkIT2r9OGoo

### No token
GET http://localhost:5000/api/favorites

### Invalid token
GET http://localhost:5000/api/favorites
Authorization: Bearer invalidtoken123

### Save GIF
POST http://localhost:5000/api/favorites
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMDRiZGFkMDcxZWZiYmNhYTJjM2RkNiIsInVzZXJuYW1lIjoib2xpdmVyand0IiwiZW1haWwiOiJvbGl2ZXJqd3RAZXhhbXBsZS5jb20iLCJpYXQiOjE3Nzg3ODE3ODIsImV4cCI6MTc3ODc4NTM4Mn0.4j2cNlLrUUHAulY5NPLN9K404YGS1ihgELTa_1hE-Ss
Content-Type: application/json

{
  "gifId": "abc123"
}

### Get favorites
GET http://localhost:5000/api/favorites
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMDRiZGFkMDcxZWZiYmNhYTJjM2RkNiIsInVzZXJuYW1lIjoib2xpdmVyand0IiwiZW1haWwiOiJvbGl2ZXJqd3RAZXhhbXBsZS5jb20iLCJpYXQiOjE3Nzg3ODE3ODIsImV4cCI6MTc3ODc4NTM4Mn0.4j2cNlLrUUHAulY5NPLN9K404YGS1ihgELTa_1hE-Ss

### Remove GIF
DELETE http://localhost:5000/api/favorites/abc123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMDRiZGFkMDcxZWZiYmNhYTJjM2RkNiIsInVzZXJuYW1lIjoib2xpdmVyand0IiwiZW1haWwiOiJvbGl2ZXJqd3RAZXhhbXBsZS5jb20iLCJpYXQiOjE3Nzg3ODE3ODIsImV4cCI6MTc3ODc4NTM4Mn0.4j2cNlLrUUHAulY5NPLN9K404YGS1ihgELTa_1hE-Ss


### Test /api/me
GET http://localhost:5000/api/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMDRiZGFkMDcxZWZiYmNhYTJjM2RkNiIsInVzZXJuYW1lIjoib2xpdmVyand0IiwiZW1haWwiOiJvbGl2ZXJqd3RAZXhhbXBsZS5jb20iLCJpYXQiOjE3Nzg4NzE0MDAsImV4cCI6MTc3ODg3NTAwMH0.XtVIPcRzePJDpToq5goAjlAcjr56zcHd7GKUHBaIc2Y


